# Generated by Django 4.0.2 on 2022-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_post_slug_alter_post_tags_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='c2.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
